name: Stoxify CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: stock-trading-api/package-lock.json
    
    - name: Install dependencies
      working-directory: ./stock-trading-api
      run: npm ci
    
    - name: Run tests
      working-directory: ./stock-trading-api
      run: npm test
    
    - name: Generate test coverage
      working-directory: ./stock-trading-api
      run: npm run test:coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./stock-trading-api/coverage
        flags: unittests
        name: codecov-umbrella

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: stock-trading-api/package-lock.json
    
    - name: Install dependencies
      working-directory: ./stock-trading-api
      run: npm ci
    
    - name: Run ESLint (if configured)
      working-directory: ./stock-trading-api
      run: npm run lint --if-present

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: stock-trading-api/package-lock.json
    
    - name: Install dependencies
      working-directory: ./stock-trading-api
      run: npm ci
    
    - name: Build application
      working-directory: ./stock-trading-api
      run: npm run build --if-present
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: |
          stock-trading-api/dist/
          frontend/